Juice 30 and juice 44 save and load functionality
Aeronautical-Axolotls/JuiceBox pull request #52
Opened 2024-03-30 04:26 UTC by MatthewFisk

Save and load are now in a workable state.

UI buttons "Load" and "Save As" have functionality. Pressing them will open their respective file dialogs, where you can select a file.

The main change is the plugin file_system.rs. It uses bevy's state system to remember which state it's in, Loading, Saving, or Running, and calls the correct save or load functions depending on that. I cannot call them on normal schedules because they have direct read/write access to the world. The actual saving and loading use bevy_save, which helps with a Pipeline and custom file formats (which I'm just using for the file extension right now). The file dialogs are made using rfd (Rust File Dialogs) library.

The actual file format is truly just .json, but I've renamed the file extension to .juice. Can be changed to something else if you guys want. Right now I have my test files in /assets/scenes. In /load_test are some older files that I made by manually editing them. Most of the files in save_test are not edited, except for the "oh no im trapped.juice" file.

Some things that are currently not working:
- Regular "Save" does not work because file_system doesn't save the current file right now.
- Cannot currently invoke a direct call to init_loading() with a preset filepath, so we can't set a default file or last used file right on startup. I can probably just save the default and most recent files in a metadata file somewhere, but relying on that would make the function less flexible.
- When the particles hit the ground I get this error: "WARN bevy_ecs::world: error[B0003]: Could not despawn entity 319v1 because it doesn't exist in this World." But it doesn't seem to be actually affecting anything at all as far as I can tell.
- The particles move strangely on the load of a file, to varying degrees.
- In some of the save files the velocities in SimGrid seem to be off. Insane numbers like -3.4028235e38 while some are 0.0019996716. Go to line 63732 in "interger overflow in entity count.juice" for an example. This is likely what's causing some funky moves of the particles
- Also, in that file the entities start count at 4294967299. I have no idea why or how to replicate it.

None of this bugginess that I've found has an impact on the performance of the first startup of the simulation at all, it only comes up when you try to load a file.

2024-04-01 06:12 UTC, r3dc0g commented
Tested and works well! Thanks Matthew! 

Though, I don't think we need to keep test save files in the repo. If you want to add that folder to the git ignore, you could still work with them. I also think your vscode settings folder can be added to the git ignore. 

What's up with test.scn.ron ?

2024-04-01 18:58 UTC, Dillon-Goicoechea requested changes
Looks like it is going in the right direction!

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on assets/scenes/load_test/test_load_11_friends.juice
We should git ignore all non-UI assets.

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/file_system.rs
> +        app.register_type::<(u16, u16)>();
what is this for?

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/file_system.rs
> +        app.register_type::<Vec<f32>>();
please add comments for non explicitly named objects

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/file_system.rs
> +        app.add_systems(OnEnter(JuiceStates::Loading), load_scene);
what are these doing?

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/file_system.rs
> +impl Pipeline for JuicePipeline {
Please add comments explaining what each function is doing explicitly

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/file_system.rs
> +    if (key.is_some()) {
is there a more clear or effective form of verification?

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/file_system.rs
> +/// UNFINISHED FUNCTIONALITY - If a String is passed in the key argument, load that function. Otherwise run a file dialog asking the user.
what part is unfinished?

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/file_system.rs
> +    if (key.is_some()) {
same concern as above

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/file_system.rs
> +            .unwrap()[0]
if any error is encountered this will crash the program

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/file_system.rs
> +    if (selected_path.is_some()) {
same concern as above

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/file_system.rs
> +        key.truncate(key.len() - 6); // Removing the .juice file extension, bevy_save breaks otherwise.
Can we please verify the key exists before attempting truncation?

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/file_system.rs
> +            .unwrap()
same issue as before

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/file_system.rs
> +        key.truncate(key.len() - 6); // Removing the .juice file extension, bevy_save breaks otherwise.
same issue as before

2024-04-01 18:58 UTC, Dillon-Goicoechea commented on src/test.scn.ron
Please remove

2024-04-01 19:12 UTC, kadealicious commented
- Pls remove all unwrap() and expect() calls; a bad filepath/save file should not crash the program.
- There are a few sections with repeated code; see create_new_file() and get_file().  Putting some repeated code within smaller functions to increase readability is much preferred.
- // Comments comments comments comments comments comments pls
- /* Super long multi line comments are even preferred over no comments (We don't know how saving/loading works within this system, so it would be really hard for anyone else to make additions/upgrades/changes to the system without comments) */

2024-04-16 00:49 UTC, r3dc0g requested changes
Thanks, Matthew! I added my last requests for changes as some were missed.

2024-04-16 00:49 UTC, r3dc0g commented on .vscode/launch.json
please put .vscode in .gitignore

2024-04-16 00:49 UTC, r3dc0g commented on assets/scenes/load_test/test_load_no_particles_all_solid.juice
Also add testing save files to .gitignore

2024-04-16 00:49 UTC, r3dc0g commented on src/test.scn.ron
Remove this file

2024-04-17 00:59 UTC, r3dc0g submitted a review, later dismissed

2024-04-17 02:43 UTC, Dillon-Goicoechea approved these changes
lgtm

2024-04-17 02:46 UTC, merged